server:
  port: 9000

# GraphQL
com.merapar.graphql:
  rootQueryName: "queries"
  rootQueryDescription: ""
  rootMutationName: "mutations"
  rootMutationDescription: ""
  requestMapping:
    path: "/v1/graphql"
  executor:
    minimumThreadPoolSizeQuery: 10
    maximumThreadPoolSizeQuery: 20
    keepAliveTimeInSecondsQuery: 30
    minimumThreadPoolSizeMutation: 10
    maximumThreadPoolSizeMutation: 20
    keepAliveTimeInSecondsMutation: 30
    minimumThreadPoolSizeSubscription: 10
    maximumThreadPoolSizeSubscription: 20
    keepAliveTimeInSecondsSubscription: 30